name: integration tests

on:
  - push
  - pull_request
  - workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    name: integration tests
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: pip install -e .
    - name: Install packages needed for tests
      # pyright 1.1.336 can produce annoying errors
      run: pip install pytest pytest-cov pyright==1.1.335
    - name: Install pynwb needed for tests
      run: pip install pynwb
    - name: Run pyright
      run: cd lindi && pyright
    - name: Run tests and collect coverage
      run: pytest --cov lindi --cov-report=xml --cov-report=term tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NeurodataWithoutBorders/lindi