name: integration tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: integration tests
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: pip install .
    - name: Install packages needed for tests
      run: pip install pytest pytest-cov
    - name: Install pynwb needed for tests
      run: pip install pynwb
    - name: Run tests and collect coverage
      run: pytest --cov lindi --cov-report=xml --cov-report=term tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NeurodataWithoutBorders/lindi