name: linter-checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linter checks
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: pip install .
    - name: Install packages needed for tests
      run: pip install flake8 pytest
    - name: Run flake8
      run: cd lindi && flake8 --config ../.flake8
